### ISSUE TITLE
安装此插件后，无法打开build.gradle文件

### ISSUE THREAD

**Issue by meiMingle** [TonyLiu0112/donate#1]
Windows10
idea2023.2.1
打开的项目地址 https://github.com/meiMingle/ScreenSnap

```java
  Unhandled exception in [CoroutineName(com.intellij.ui.EditorNotificationsImpl), ANY, StandaloneCoroutine{Cancelling}@65d0d30, Dispatchers.EDT]
  
  java.lang.AssertionError: Wrong line separators: 'plugins {\r\n    id '...' at offset 9
at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2484)
at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:706)
at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:124)
at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:119)
at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:110)
at com.intellij.openapi.editor.impl.EditorFactoryImpl.createDocument(EditorFactoryImpl.java:129)
at com.tony.liu.plugins.gradle.tree.editor.GradleTreeEditor.createEditorComponent(GradleTreeEditor.kt:88)
at com.tony.liu.plugins.gradle.tree.editor.GradleTreeEditor.doInit(GradleTreeEditor.kt:40)
at com.tony.liu.plugins.gradle.tree.editor.GradleTreeEditor.getComponent(GradleTreeEditor.kt:64)
at com.intellij.ui.EditorNotificationsImpl$doUpdateNotifications$1.invoke(EditorNotificationsImpl.kt:158)
at com.intellij.ui.EditorNotificationsImpl$doUpdateNotifications$1.invoke(EditorNotificationsImpl.kt:157)
at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
at com.intellij.ui.EditorNotificationsImpl.doUpdateNotifications(EditorNotificationsImpl.kt:165)
at com.intellij.ui.EditorNotificationsImpl.access$doUpdateNotifications(EditorNotificationsImpl.kt:42)
at com.intellij.ui.EditorNotificationsImpl$updateNotifications$1.invokeSuspend(EditorNotificationsImpl.kt:149)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:193)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(com.intellij.ui.EditorNotificationsImpl), ANY, StandaloneCoroutine{Cancelled}@65d0d30, Dispatchers.EDT]
```

**Comment by TonyLiu0112** [comment]
<img width="1043" alt="image" src="https://github.com/TonyLiu0112/donate/assets/17778895/8be5187a-aa7e-4024-945c-359379abc6aa">

在我mac上是正常的,可能是对windows的支持不太好, 我得找个windows机器来复现一下 😂

**Comment by TonyLiu0112** [comment]
我使用windows10、11均测试过，并未复现此问题。
考虑是否是本地文件的字符问题？或者试试重启一下idea在打开gradle文件

**Comment by TonyLiu0112** [comment]
it was a bug for file line separator mode. 

**you can set file line separator mode to `LF`**

This bug will be resolved in version `1.0.3`

**Comment by TonyLiu0112** [comment]
`1.0.3` has been released
